import {
  bigserial,
  boolean,
  doublePrecision,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
} from "drizzle-orm/pg-core";

export const networkProviderSnapshotTable = pgTable("network_provider_snapshot", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  externalId: integer("external_id"),
  name: text("name").notNull(),
  organizationName: text("organization_name"),
  siteName: text("site_name"),
  siteDisplay: text("site_display"),
  facilityType: text("facility_type"),
  networkStatus: text("network_status"),
  visible: boolean("visible"),
  country: text("country"),
  stateRegion: text("state_region"),
  city: text("city"),
  county: text("county"),
  address1: text("address1"),
  address2: text("address2"),
  postalCode: text("postal_code"),
  latitude: doublePrecision("latitude"),
  longitude: doublePrecision("longitude"),
  coordinateQuality: text("coordinate_quality"),
  phone: text("phone"),
  fax: text("fax"),
  contactName: text("contact_name"),
  timezone: text("timezone"),
  hoursScheduling: text("hours_scheduling"),
  billingTerms: text("billing_terms"),
  sourceCreatedAt: text("source_created_at"),
  sourceCreatedBy: text("source_created_by"),
  harvest: text("harvest"),
  services: jsonb("services").notNull().default([]),
  lastAppointment: text("last_appointment"),
  pricingAvailable: boolean("pricing_available").notNull().default(false),
  agreementComponentIds: text("agreement_component_ids"),
  serviceComponentIds: text("service_component_ids"),
  activity2026: text("activity_2026"),
  activity2026Category: text("activity_2026_category"),
  agreement2026: text("agreement_2026"),
  agreementDate2026: text("agreement_date_2026"),
  pricingServiceComponents2026: text("pricing_service_components_2026"),
  internalNotes: text("internal_notes"),
  examineeInstructions: text("examinee_instructions"),
  auditHistory: text("audit_history"),
  sourceStatus: text("source_status"),
  importedAt: timestamp("imported_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index("network_provider_snapshot_geo_idx").on(table.country, table.stateRegion, table.city),
  index("network_provider_snapshot_status_idx").on(table.networkStatus),
]);

export const networkPricingSnapshotTable = pgTable("network_pricing_snapshot", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  canonicalExternalId: integer("canonical_external_id"),
  networkName: text("network_name"),
  siteName: text("site_name"),
  address1: text("address1"),
  address2: text("address2"),
  city: text("city"),
  stateRegion: text("state_region"),
  postalCode: text("postal_code"),
  phone: text("phone"),
  country: text("country"),
  providerType: text("provider_type"),
  componentName: text("component_name").notNull(),
  numericPrice: doublePrecision("numeric_price"),
  sourcePriceText: text("source_price_text"),
  effectiveDate: text("effective_date"),
  expirationDate: text("expiration_date"),
  lineItemCreated: text("line_item_created"),
  importedAt: timestamp("imported_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index("network_pricing_snapshot_external_idx").on(table.canonicalExternalId),
  index("network_pricing_snapshot_geo_idx").on(table.country, table.stateRegion, table.city),
  index("network_pricing_snapshot_component_idx").on(table.componentName),
]);

export const networkAvailabilitySnapshotTable = pgTable("network_availability_snapshot", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  canonicalExternalId: integer("canonical_external_id"),
  networkName: text("network_name"),
  siteName: text("site_name"),
  address1: text("address1"),
  address2: text("address2"),
  city: text("city"),
  stateRegion: text("state_region"),
  postalCode: text("postal_code"),
  phone: text("phone"),
  country: text("country"),
  providerType: text("provider_type"),
  componentName: text("component_name").notNull(),
  componentType: text("component_type"),
  importedAt: timestamp("imported_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index("network_availability_snapshot_external_idx").on(table.canonicalExternalId),
  index("network_availability_snapshot_geo_idx").on(table.country, table.stateRegion, table.city),
  index("network_availability_snapshot_component_idx").on(table.componentName),
]);

export const networkDatasetStateTable = pgTable("network_dataset_state", {
  datasetKey: text("dataset_key").primaryKey(),
  sourceSha256: text("source_sha256").notNull(),
  providerCount: integer("provider_count").notNull(),
  pricingCount: integer("pricing_count").notNull(),
  availabilityCount: integer("availability_count").notNull(),
  loadedAt: timestamp("loaded_at", { withTimezone: true }).notNull().defaultNow(),
});
