import {
  bigserial,
  boolean,
  doublePrecision,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
} from "drizzle-orm/pg-core";

export const networkProviderSnapshotTable = pgTable("network_provider_snapshot", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  externalId: integer("external_id"),
  name: text("name").notNull(),
  organizationName: text("organization_name"),
  siteName: text("site_name"),
  facilityType: text("facility_type"),
  networkStatus: text("network_status"),
  visible: boolean("visible"),
  country: text("country"),
  stateRegion: text("state_region"),
  city: text("city"),
  address1: text("address1"),
  address2: text("address2"),
  postalCode: text("postal_code"),
  latitude: doublePrecision("latitude"),
  longitude: doublePrecision("longitude"),
  phone: text("phone"),
  services: jsonb("services").notNull().default([]),
  lastAppointment: text("last_appointment"),
  pricingAvailable: boolean("pricing_available").notNull().default(false),
  agreementComponentIds: text("agreement_component_ids"),
  serviceComponentIds: text("service_component_ids"),
  activity2026: text("activity_2026"),
  sourceStatus: text("source_status"),
  importedAt: timestamp("imported_at", { withTimezone: true }).notNull().defaultNow(),
});

export const networkPricingSnapshotTable = pgTable("network_pricing_snapshot", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  canonicalExternalId: integer("canonical_external_id"),
  networkName: text("network_name"),
  siteName: text("site_name"),
  address1: text("address1"),
  address2: text("address2"),
  city: text("city"),
  stateRegion: text("state_region"),
  postalCode: text("postal_code"),
  phone: text("phone"),
  country: text("country"),
  providerType: text("provider_type"),
  componentName: text("component_name").notNull(),
  numericPrice: doublePrecision("numeric_price"),
  sourcePriceText: text("source_price_text"),
  effectiveDate: text("effective_date"),
  expirationDate: text("expiration_date"),
  lineItemCreated: text("line_item_created"),
  importedAt: timestamp("imported_at", { withTimezone: true }).notNull().defaultNow(),
});

export const networkAvailabilitySnapshotTable = pgTable("network_availability_snapshot", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  canonicalExternalId: integer("canonical_external_id"),
  networkName: text("network_name"),
  siteName: text("site_name"),
  address1: text("address1"),
  address2: text("address2"),
  city: text("city"),
  stateRegion: text("state_region"),
  postalCode: text("postal_code"),
  phone: text("phone"),
  country: text("country"),
  providerType: text("provider_type"),
  componentName: text("component_name").notNull(),
  componentType: text("component_type"),
  importedAt: timestamp("imported_at", { withTimezone: true }).notNull().defaultNow(),
});

export const networkDatasetStateTable = pgTable("network_dataset_state", {
  datasetKey: text("dataset_key").primaryKey(),
  sourceSha256: text("source_sha256").notNull(),
  providerCount: integer("provider_count").notNull(),
  pricingCount: integer("pricing_count").notNull(),
  availabilityCount: integer("availability_count").notNull(),
  loadedAt: timestamp("loaded_at", { withTimezone: true }).notNull().defaultNow(),
});
